# Generated by Django 4.0.4 on 2022-12-17 08:34

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_date_posted_remove_post_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 8, 34, 56, 107400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_likes',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
