# Generated by Django 4.0.4 on 2022-12-21 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_post_date_posted_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 40, 21, 543568, tzinfo=utc)),
        ),
    ]
